/** Auto-generated file */

export const nitroPresets = [
  "alwaysdata",
  "aws-amplify",
  "aws-lambda",
  "azure-functions",
  "azure-swa",
  "bun",
  "cleavr",
  "cli",
  "cloudflare-dev",
  "cloudflare-durable",
  "cloudflare-module",
  "cloudflare-module-legacy",
  "cloudflare-pages",
  "cloudflare-pages-static",
  "cloudflare-worker",
  "deno-deploy",
  "deno-server",
  "deno-server-legacy",
  "digital-ocean",
  "edgio",
  "firebase",
  "firebase-app-hosting",
  "flight-control",
  "genezio",
  "github-pages",
  "gitlab-pages",
  "heroku",
  "iis-handler",
  "iis-node",
  "koyeb",
  "netlify",
  "netlify-builder",
  "netlify-edge",
  "netlify-legacy",
  "netlify-static",
  "node-cluster",
  "node-listener",
  "node-server",
  "platform-sh",
  "render-com",
  "service-worker",
  "static",
  "stormkit",
  "vercel",
  "vercel-edge",
  "vercel-static",
  "winterjs",
  "zeabur",
  "zeabur-static",
  "zerops",
  "zerops-static"
] as const

export const templates = [
  "doc-driven",
  "hub",
  "layer",
  "module",
  "module-devtools",
  "ui",
  "ui-vue",
  "v2-bridge",
  "v3",
  "v4",
  "v4-compat"
] as const
