name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🛠 Build project
        run: pnpm build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@df47568b033d58cefcc54680a649123fc87b7573 # v4.10.1
        with:
          run: pnpm vitest bench
          mode: instrumentation
          token: ${{ secrets.CODSPEED_TOKEN }}
